defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: gredients_development

test:
  <<: *defaults
  database: gredients_test